- include_vars: user.yml
- include_vars: fs.yml

- include_tasks: system/btrfs.yml

- block:
    # KDE tasks
    - include_tasks: kde/hid.yml
    - include_tasks: kde/keybinds.yml

    # Install all software
    - include_tasks: software.yml
