- name: Software | Dev | Install editors
  tags: software,dev,editors,cli,gui
  pacman:
    executable: paru # Use AUR helper instead of pacman
    reason: explicit
    reason_for: all
    become: yes
    name:
        - neovim
        - micro
        - zed
        - cursor-bin

- name: Software | Dev | Install tools
  tags: software,dev,tools,cli,gui
  pacman:
    executable: paru # Use AUR helper instead of pacman
    reason: explicit
    reason_for: all
    become: yes
    name:
        - git
        - lazygit # GUI for git, might be useful
        - docker
        - bruno-bin # Postman alternative
        - meld

- name: Software | Dev | Install languages
  tags: software,languages,cli
  pacman:
    reason: explicit
    reason_for: all
    become: yes
    name:
        - python
        - nodejs
        - go
        - rustup
        - jdk-openjdk
        - deno
        - yarn
        - uv
