- name: Software | Dev | Install editors
  tags: software,dev,editors,cli,gui
  kewlfft.aur.aur:
    name:
        - neovim
        - micro
        - zed
        - cursor-bin

- name: Software | Dev | Install tools
  tags: software,dev,tools,cli,gui
  kewlfft.aur.aur:
    name:
        - git
        - lazygit # GUI for git, might be useful
        - docker
        - bruno-bin # Postman alternative
        - meld

- name: Software | Dev | Install languages
  tags: software,languages,cli
  kewlfft.aur.aur:
    name:
        - python
        - nodejs
        - go
        - rustup
        - jdk-openjdk
        - deno
        - yarn
        - uv
