- name: Software | Media | Install Media players
  tags: software,media,gui
  pacman:
    executable: paru # Use AUR helper instead of pacman for feishin and fladder
    reason: explicit
    reason_for: all
    become: yes
    name:
        - vlc
        - mpv
        - haruna
        - feishin-bin
        - fladder-bin

- name: Software | Media | Install media editors
  tags: software,media,gui
  pacman:
    reason: explicit
    reason_for: all
    become: yes
    name:
        - audacity
        - kdenlive
        - ffmpeg
        - handbrake
        - kolourpaint
        - gimp
        - obs-studio
