- name: Software | Messaging | Install messaging apps
  tags: software,messaging,gui
  pacman:
    executable: paru # Use AUR helper instead of pacman for vesktop
    reason: explicit
    reason_for: all
    become: yes
    name:
        - vesktop-bin
        - telegram-desktop
        - zoom
