- name: Software | Tools | Install GUI system tools
  tags: software,tools,gui
  kewlfft.aur.aur:
    name:
      - partitionmanager # Should be installed already
      - filelight # Ditto
      # - cheese # Camera utility
      - helvum # Audio patch panel
      - yakuake
      - qbittorrent
      - wireshark-qt
      - virt-manager

- name: Software | Tools | Install CLI tools
  tags: software,tools,cli
  kewlfft.aur.aur:
    name:
      - wget
      - curl
      - aria2
      - tmux
      - rsync
      - nmap
      - gnupg
      - flatpak
      - btrbk
      - superfile
      - tree
