- name: Software | Media | Install Media players
  tags: software,media,gui
  kewlfft.aur.aur:
    name:
        - vlc
        - mpv
        - haruna
        - feishin-bin
        - fladder-bin

- name: Software | Media | Install media editors
  tags: software,media,gui
  kewlfft.aur.aur:
    name:
        - audacity
        - kdenlive
        - ffmpeg
        - handbrake
        - kolourpaint
        - gimp
        - obs-studio
