- name: Software | Homelab | Install tools
  tags: software,homelab,tools,cli,gui
  kewlfft.aur.aur:
    name:
      - wireguard-tools
      - syncthingtray-qt6
      - syncthingctl-bin # Useful CLI controller
      - syncthing-resolve-conflicts
      - bitwarden
