# tasks to complete before running roles
- hosts: all
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | update pacman package cache
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_facts['distribution'] == "Archlinux"
      become: yes

# run roles
- hosts: all
  tags: base
  roles:
    - base

- hosts: all
  tags: desktop
  roles:
    - desktop
#
# - hosts: laptop
#   tags: laptop
#   become: true
#   roles:
#     - laptop
#
# - hosts: server
#   tags: server
#   become: true
#   roles:
#     - server

